config/routes.rb
Rails.application.routes.draw do

  get 'static_clients/home'

  get 'static_clients/about'

  root 'static_clients#home'

  get '/about', to: 'static_clients#about'

resources :clients
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  def index
    @clients = Client.all
  end

  def show
    @client = Client.find(params[:id])
  end

  def new
    @client = Client.new
  end

  def create
  @client = Client.new(clients_params)

    if @client.save
      redirect_to =clients_path
    else
      render :new
    end
  end

  def edit
    @client = Client.find(params[:id])
  end

  def update
    @client = Client.find(params[:id])

    if @client.update(clients_params)
      redirect_to clients_path
    else
      render :edit
    end
  end

  def destroy
    Client.find(params[:id]).destroy
    redirect_to client_path
  end

  private

  def clients_params
    params.require(:client).permit(:name, :age, :hair_color, :eye_color, :gender)
  end
end

app/controllers/static_clients_controller.rb
class StaticClientsController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/static_clients_helper.rb
module StaticClientsHelper
end

app/views/clients/edit.html.erb
<h1>Edit Client</h1>
<%= form_for @client do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :age %>
  <%= f.text_field :age %>

  <%= f.label :hair_color %>
  <%= f.text_area :hair_color %>

  <%= f.label :eye_color %>
  <%= f.text_area :eye_color %>

  <%= f.label :gender %>
  <%= f.text_area :gender %>

  <%= f.submit %>
<% end %>

app/views/clients/index.html.erb
<h1> Clients </h1>
<p><%= link_to 'New Client', new_client_path %></p>
<% @clients.each do |client| %>
  <h2><%= client.name %></h2>
  <%= link_to 'Show Client', client_path(client) %>
  <%= link_to 'Edit Client', edit_client_path(client) %>
  <%= link_to 'Destroy Client', client_path(client), method: :delete %>
<% end %>

app/views/clients/new.html.erb
<h1>New Client</h1>
<%= form_for @client do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :age %>
  <%= f.text_field :age %>

  <%= f.label :hair_color %>
  <%= f.text_area :hair_color %>

  <%= f.label :eye_color %>
  <%= f.text_area :eye_color %>

  <%= f.label :gender %>
  <%= f.text_area :gender %>

  <%= f.submit %>
<% end %>

app/views/clients/show.html.erb
<h1><%= @client.name %></h1>
<h4><%= @client.age %></h1>
<p><%= @client.hair_color %></p>
<p><%= @client.eye_color %></p>
<p><%= @client.gender %></p>
<%= link_to 'Back', clients_path %>

app/views/layouts/_navbar.html.erb
<%= link_to 'Home', root_path %>
<%= link_to 'About', about_path %>
<%= link_to 'Clients', clients_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ClientList</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/static_clients/about.html.erb
<h1>StaticClients#about</h1>
<p>Find me in app/views/static_clients/about.html.erb</p>

app/views/static_clients/home.html.erb
<h1>StaticClients#home</h1>
<p>Find me in app/views/static_clients/home.html.erb</p>